default: all

all:
	rm -f aclocal.m4 config.guess config.sub ltmain.sh depcomp install-sh mkinstalldirs ltconfig missing  
	libtoolize --automake
	aclocal
	autoheader
	automake --add-missing
	autoconf
	@echo "printing README"
	@echo "" 
	cat README
	@echo "printing src/readme.txt"
	@echo "" 
	cat src/readme.txt

