default: all

all:
	rm -f config.guess config.sub ltmain.sh
	libtoolize --automake
	aclocal
	autoheader
	automake --add-missing
	autoconf
	@echo "printing README"
	@echo "" 
	cat README
	@echo "printing src/readme.txt"
	@echo "" 
	cat src/readme.txt

